<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.rocwg</groupId>
        <artifactId>at-build</artifactId>
        <version>${revision}</version>
        <relativePath>./at-build/pom.xml</relativePath>
    </parent>

    <artifactId>jaro-samples-grpc</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>grpc-api-contract</module>
        <module>grpc-client</module>
        <module>grpc-server</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.rocwg</groupId>
                <artifactId>grpc-api-contract</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
