<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<!-- ========================= -->
	<!-- Parent -->
	<!-- ========================= -->
	<parent>
		<groupId>io.github.rocwg</groupId>
		<artifactId>jaro-samples-grpc</artifactId>
		<version>${revision}</version>
	</parent>

	<artifactId>grpc-server</artifactId>
	<packaging>jar</packaging>

	<name>grpc-server</name>

	<!-- ========================= -->
	<!-- Dependencies -->
	<!-- ========================= -->
	<dependencies>

		<!-- contract -->
		<dependency>
			<groupId>io.github.rocwg</groupId>
			<artifactId>grpc-contract</artifactId>
		</dependency>

		<!-- spring boot -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<!-- gRPC Server -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-grpc-server</artifactId>
		</dependency>

		<!-- Actuator -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<!-- test -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

	</dependencies>

	<!-- ========================= -->
	<!-- Build -->
	<!-- ========================= -->
	<build>

		<plugins>

			<!-- spring boot -->
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>

		</plugins>

	</build>

</project>
