<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>io.github.rocwg</groupId>
		<artifactId>jaro-samples-grpc</artifactId>
		<version>${revision}</version>
	</parent>

	<artifactId>grpc-client</artifactId>
	<packaging>jar</packaging>

	<name>grpc-client</name>

	<!-- ========================= -->
	<!-- Dependencies -->
	<!-- ========================= -->
	<dependencies>
		<!-- Contract -->
		<dependency>
			<groupId>io.github.rocwg</groupId>
			<artifactId>grpc-contract</artifactId>
		</dependency>

		<!-- Spring Boot Core -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<!-- gRPC Client -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-grpc-client</artifactId>
		</dependency>
	</dependencies>

	<!-- ========================= -->
	<!-- Build -->
	<!-- ========================= -->
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
