spring:
  application:
    name: grpc-client
  grpc:
    client:
      channel:
        #################################################################
        #default: # 这是一个特殊的保底 Key
        #  target: "static://0.0.0.0:${launched.grpc.port:9090}"
        #################################################################
        # 通道1：对应 Hello 服务的地址
        hello-service:
          target: "static://localhost:9090"
        # 通道2：对应认证服务的地址（即便现在相同，生产也往往不同）
        authentication-service:
          target: "static://localhost:9090"
